### ISSUE TITLE
AutoDoc is looking for doc/Toric.xml

### ISSUE THREAD

**Issue by jgmbenoit** [gap-packages/toric#8]
When the below script inspired by makedoc.g

## 
SetPackagePath("toric",".");
LoadPackage("autodoc");;
LoadPackage("toric");;
AutoDoc(rec(scaffold:=rec(MainPage:=false)));
##

is launched as follows

cat <SCRIPT> | gap -A -q -T

I get
Generating documentation in Directory("./doc/")
#I Composing XML document . . .
Error, Cannot include file ./doc/Toric.xml.

As workaround, I create a link, but I guess that the issue somewhere else .

**Comment by fingolfin** [comment]
Hu, it seems somehow I never saw this issue. It was fixed in d45211f3a3ab14d5135ead64c9b3cf0d028a971b (so a few years ago, and a few years after this issue was opened) but nobody remembered to make a release of this package. I'll take care of that that 

BTW, you don't need to load `toric` in order to run `AutoDoc`. It suffices to run `makedoc.g` with PWD set to the directory containing it. And then you can just use unmodified `makedoc.g` file.
